driver = "sqlite" # change to postgres if u want to use psql
sqlite_path = "data/mesa.db"
jwt_secret_key = "super-secret-key" # generate JWT secret key with `openssl rand -hex 32`

server_domain = "localhost:8080"

# do not uncomment it unless you are using postgresql
#postgres_dsn = "postgres://mesa_user:ilovemesaproject@localhost:5432/mesa?sslmode=disable"
